# @package _global_

defaults:
  - classification_base


dataset:
  name: swissprot
  simple_cls:
    _target_: datasets.prot.swissprot.SPSimpleDataset

  set_cls:
    _target_: datasets.prot.swissprot.SPSetDataset


backbone:
  _target_: backbones.fcnet.FCNet
  layer_dim: [128, 128]


train_classes: 59

n_way: 5
n_shot: 5
n_query: 15

